[project]
name = "spotify-backup"
version = "0.1.0"
description = "Export Spotify playlists to JSON files"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "spotipy>=2.25.0",
]

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
]
